// flow-typed signature: afe3265c463710932a55ac4037c57e90
// flow-typed version: <<STUB>>/hyperapp_v^0.7.1/flow_v0.42.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'hyperapp'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'hyperapp' {
  declare export function app(options: App): void

  declare type App = {
    model: any,
    view: View,
    actions: {
      [name: string]: (model: any, data?: any, actions?: any, error?: ErrorFunction) => any
    },
    subscriptions?: any,
    hooks?: Hooks,
    plugins?: any,
    root?: HTMLElement,
  }

  declare type View = (model: any, actions: any) => any

  declare type Hooks = {
    onAction?: (name: string, data: any) => void,
    onUpdate?: (prev: any, next: any, data: any) => void,
    onRender?: (model: any, view: View) => void,
    onError?: ErrorFunction,
  }

  declare type ErrorFunction = (error: string | Error) => void

  // TODO: vnode stuff
  declare export function h(tag: string, props: Object, children: string | mixed[]): any
}
